
# below name acts as an instance id
spring.application.name=product-catalogue-demo
server.port=8181
# connects to the config server
# spring.config.import=optional:configserver:http://localhost:8888
# spring.profiles.active=dev