spring.application.name=service-discovery-demo
# by default all the clients look for server in 8761 port
server.port=8761
# by default server downloads eureka client library 
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false